/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#line 1 "test.check"
#include "s21_grep.h"

START_TEST(emty_option) {
#line 4
system("grep include s21_grep.h > a");
system("./s21_grep include s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option1) {
#line 11
system("grep -e include s21_grep.h > a");
system("./s21_grep -e include s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option2) {
#line 16
system("grep -e include -e end s21_grep.h > a");
system("./s21_grep -e include -e end s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option3) {
#line 21
system("grep -e include -e end -e aaa s21_grep.h > a");
system("./s21_grep -e include -e end -e aaa s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option4) {
#line 26
system("grep s21_grep.h -e include > a");
system("./s21_grep s21_grep.h -e include > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option5) {
#line 31
system("grep s21_grep.h -e incl.de -e end > a");
system("./s21_grep s21_grep.h -e incl.de -e end > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option6) {
#line 36
system("grep -e include s21_grep.h s21_grep.c > a");
system("./s21_grep -e include s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option7) {
#line 41
system("grep -e include -e end s21_grep.h s21_grep.c > a");
system("./s21_grep -e include -e end s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option8) {
#line 46
system("grep -e include -e end -e aaa s21_grep.h s21_grep.c > a");
system("./s21_grep -e include -e end -e aaa s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option9) {
#line 51
system("grep s21_grep.h -e include s21_grep.c > a");
system("./s21_grep s21_grep.h -e include s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option10) {
#line 56
system("grep s21_grep.h -e incl.de -e end s21_grep.c > a");
system("./s21_grep s21_grep.h -e incl.de -e end s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(i_option1) {
#line 63
system("grep -i include s21_grep.h > a");
system("./s21_grep -i include s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(i_option2) {
#line 68
system("grep -i incLudE s21_grep.h > a");
system("./s21_grep -i incLudE s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(i_option3) {
#line 73
system("grep -i incL.dE s21_grep.h > a");
system("./s21_grep -i incL.dE s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(i_option4) {
#line 78
system("grep -i include s21_grep.h s21_grep.c > a");
system("./s21_grep -i include s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(i_option5) {
#line 83
system("grep -i incLudE s21_grep.h s21_grep.c > a");
system("./s21_grep -i incLudE s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(i_option6) {
#line 88
system("grep -i incL.dE s21_grep.h s21_grep.c > a");
system("./s21_grep -i incL.dE s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(v_option1) {
#line 95
system("grep -v include s21_grep.h > a");
system("./s21_grep -v include s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(v_option2) {
#line 100
system("grep -v inclue s21_grep.h > a");
system("./s21_grep -v inclue s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(v_option3) {
#line 105
system("grep -v int s21_grep.c > a");
system("./s21_grep -v int s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(v_option4) {
#line 110
system("grep -v include s21_grep.h s21_grep.c > a");
system("./s21_grep -v include s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(v_option5) {
#line 115
system("grep -v inclue s21_grep.h s21_grep.c > a");
system("./s21_grep -v inclue s21_grep.h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(v_option6) {
#line 120
system("grep -v int s21_grep.c s21_grep.c > a");
system("./s21_grep -v int s21_grep.c s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

START_TEST(c_option1) {
#line 126
system("grep -c -o int s21_grep.c > a");
system("./s21_grep -c -o int s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(c_option2) {
#line 131
system("grep -c include s21_grep.c > a");
system("./s21_grep -c include s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(c_option3) {
#line 136
system("grep -c aaa s21_grep.c > a");
system("./s21_grep -c aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(c_option4) {
#line 141
system("grep -c int s21_grep.c s21_grep.h > a");
system("./s21_grep -c int s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(c_option5) {
#line 146
system("grep -c include s21_grep.c s21_grep.h > a");
system("./s21_grep -c include s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(c_option6) {
#line 151
system("grep -c aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -c aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(n_option1) {
#line 158
system("grep -n aaa s21_grep.c > a");
system("./s21_grep -n aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(n_option2) {
#line 163
system("grep -n include s21_grep.c > a");
system("./s21_grep -n include s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(n_option3) {
#line 168
system("grep -n -e include -e end s21_grep.c > a");
system("./s21_grep -n -e include -e end s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(n_option4) {
#line 173
system("grep -n aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -n aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(n_option5) {
#line 178
system("grep -n include s21_grep.c s21_grep.h > a");
system("./s21_grep -n include s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(n_option6) {
#line 183
system("grep -n -e include -e end s21_grep.c s21_grep.h > a");
system("./s21_grep -n -e include -e end s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(l_option1) {
#line 190
system("grep -l aaa s21_grep.c > a");
system("./s21_grep -l aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(l_option2) {
#line 195
system("grep -l include s21_grep.c > a");
system("./s21_grep -l include s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(l_option3) {
#line 200
system("grep -l -e include -e end s21_grep.c > a");
system("./s21_grep -l -e include -e end s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(l_option4) {
#line 205
system("grep -l aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -l aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(l_option5) {
#line 210
system("grep -l include s21_grep.c s21_grep.h > a");
system("./s21_grep -l include s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(l_option6) {
#line 215
system("grep -l -e include -e end s21_grep.c s21_grep.h > a");
system("./s21_grep -l -e include -e end s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ei_option1) {
#line 222
system("grep -i -e incLude -e enD s21_grep.c > a");
system("./s21_grep -i -e incLude -e enD s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ei_option2) {
#line 227
system("grep -i -e incLude s21_grep.c -e enD > a");
system("./s21_grep -i -e incLude s21_grep.c -e enD > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ei_option3) {
#line 232
system("grep -i -e incLude s21_grep.c -e enD s21_grep.h > a");
system("./s21_grep -i -e incLude s21_grep.c -e enD s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ei_option4) {
#line 237
system("grep -i -e incLude -e enD s21_grep.c s21_grep.h > a");
system("./s21_grep -i -e incLude -e enD s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ei_option5) {
#line 242
system("grep -i -e incLude s21_grep.c -e enD s21_grep.h> a");
system("./s21_grep -i -e incLude s21_grep.c -e enD s21_grep.h> b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ei_option6) {
#line 247
system("grep -i -e incLude s21_grep.c -e enD s21_grep.h > a");
system("./s21_grep -i -e incLude s21_grep.c -e enD s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ev_option1) {
#line 254
system("grep -v -e incLude s21_grep.c -e enD s21_grep.h > a");
system("./s21_grep -v -e incLude s21_grep.c -e enD s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ev_option2) {
#line 259
system("grep -v -e incLude -e enD s21_grep.c > a");
system("./s21_grep -v -e incLude -e enD s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ev_option3) {
#line 264
system("grep -v -e ' ' s21_grep.c -e enD > a");
system("./s21_grep -v -e ' ' s21_grep.c -e enD > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ec_option1) {
#line 271
system("grep -c -e . s21_grep.c -e '.' > a");
system("./s21_grep -c -e . s21_grep.c -e '.' > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ec_option2) {
#line 276
system("grep -c -e . s21_grep.c -e '.' s21_grep.h > a");
system("./s21_grep -c -e . s21_grep.c -e '.' s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(iv_option1) {
#line 284
system("grep -i -v . s21_grep.c > a");
system("./s21_grep -i -v . s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(iv_option2) {
#line 289
system("grep -i -v inClude s21_grep.c > a");
system("./s21_grep -i -v inClude s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(iv_option3) {
#line 294
system("grep -i -v aaa s21_grep.c > a");
system("./s21_grep -i -v aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(iv_option4) {
#line 299
system("grep -i -v . s21_grep.c s21_grep.h > a");
system("./s21_grep -i -v . s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(iv_option5) {
#line 304
system("grep -i -v inClude s21_grep.c s21_grep.h > a");
system("./s21_grep -i -v inClude s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(iv_option6) {
#line 309
system("grep -i -v aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -i -v aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ic_option1) {
#line 316
system("grep -i -c aaa s21_grep.c > a");
system("./s21_grep -i -c aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ic_option2) {
#line 321
system("grep -i -c inClu.e s21_grep.c > a");
system("./s21_grep -i -c inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ic_option3) {
#line 326
system("grep inClu.e -i -c s21_grep.c  > a");
system("./s21_grep inClu.e -i -c s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ic_option4) {
#line 331
system("grep -i -c aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -i -c aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ic_option5) {
#line 336
system("grep -i -c inClu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -i -c inClu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ic_option6) {
#line 341
system("grep inClu.e -i -c s21_grep.c s21_grep.h > a");
system("./s21_grep inClu.e -i -c s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(il_option1) {
#line 349
system("grep -i -l aaa s21_grep.c > a");
system("./s21_grep -i -l aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(il_option2) {
#line 354
system("grep -i -l inClu.e s21_grep.c > a");
system("./s21_grep -i -l inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(il_option3) {
#line 359
system("grep inClu.e s21_grep.c -i -l > a");
system("./s21_grep inClu.e s21_grep.c -i -l > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(il_option4) {
#line 364
system("grep -i -l aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -i -l aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(il_option5) {
#line 369
system("grep -i -l inClu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -i -l inClu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(il_option6) {
#line 374
system("grep inClu.e s21_grep.c -i -l s21_grep.h > a");
system("./s21_grep inClu.e s21_grep.c -i -l s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(in_option1) {
#line 382
system("grep -i -n aaa s21_grep.c > a");
system("./s21_grep -i -n aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(in_option2) {
#line 387
system("grep -i -n inClu.e s21_grep.c > a");
system("./s21_grep -i -n inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(in_option3) {
#line 392
system("grep inClu.e s21_grep.c -i -n > a");
system("./s21_grep inClu.e s21_grep.c -i -n > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(in_option4) {
#line 397
system("grep -i -n aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -i -n aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(in_option5) {
#line 402
system("grep -i -n inClu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -i -n inClu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(in_option6) {
#line 407
system("grep inClu.e s21_grep.c -i -n s21_grep.h > a");
system("./s21_grep inClu.e s21_grep.c -i -n s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vc_option1) {
#line 414
system("grep -v -c aaa s21_grep.c > a");
system("./s21_grep -v -c aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vc_option2) {
#line 419
system("grep -v -c inClu.e s21_grep.c > a");
system("./s21_grep -v -c inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vc_option3) {
#line 424
system("grep inClu.e s21_grep.c -v -c > a");
system("./s21_grep inClu.e s21_grep.c -v -c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vc_option4) {
#line 429
system("grep -v -c aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -v -c aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vc_option5) {
#line 434
system("grep -v -c inClu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -v -c inClu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vc_option6) {
#line 439
system("grep inClu.e s21_grep.c -v -c s21_grep.h > a");
system("./s21_grep inClu.e s21_grep.c -v -c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vl_option1) {
#line 446
system("grep -v -l aaa s21_grep.c > a");
system("./s21_grep -v -l aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vl_option2) {
#line 451
system("grep -v -l inClu.e s21_grep.c > a");
system("./s21_grep -v -l inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vl_option3) {
#line 456
system("grep inClu.e s21_grep.c -v -l > a");
system("./s21_grep inClu.e s21_grep.c -v -l > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vl_option4) {
#line 461
system("grep -v -l aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -v -l aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vl_option5) {
#line 466
system("grep -v -l inClu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -v -l inClu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vl_option6) {
#line 471
system("grep inClu.e s21_grep.c -v -l s21_grep.h > a");
system("./s21_grep inClu.e s21_grep.c -v -l s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vn_option1) {
#line 479
system("grep -v -n aaa s21_grep.c > a");
system("./s21_grep -v -n aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vn_option2) {
#line 484
system("grep -v -n inClu.e s21_grep.c > a");
system("./s21_grep -v -n inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(vn_option3) {
#line 489
system("grep inClu.e s21_grep.c -v -n > a");
system("./s21_grep inClu.e s21_grep.c -v -n > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(cl_option1) {
#line 496
system("grep -c -l aaa s21_grep.c > a");
system("./s21_grep -c -l aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(cl_option2) {
#line 501
system("grep -c -l inClu.e s21_grep.c > a");
system("./s21_grep -c -l inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(cl_option3) {
#line 506
system("grep inClu.e s21_grep.c -c -l > a");
system("./s21_grep inClu.e s21_grep.c -c -l > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(cn_option1) {
#line 513
system("grep -c -n aaa s21_grep.c > a");
system("./s21_grep -c -n aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(cn_option2) {
#line 518
system("grep -c -n inClu.e s21_grep.c > a");
system("./s21_grep -c -n inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(cn_option3) {
#line 523
system("grep inClu.e s21_grep.c -c -n > a");
system("./s21_grep inClu.e s21_grep.c -c -n > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ln_option1) {
#line 530
system("grep -n -l aaa s21_grep.c > a");
system("./s21_grep -n -l aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ln_option2) {
#line 535
system("grep -n -l inClu.e s21_grep.c > a");
system("./s21_grep -n -l inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(nl_option3) {
#line 540
system("grep inClu.e s21_grep.c -n -l > a");
system("./s21_grep inClu.e s21_grep.c -n -l > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(he_option1) {
#line 547
system("grep -h -e aaa s21_grep.c > a");
system("./s21_grep -h -e aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(he_option2) {
#line 552
system("grep -h -e inclu.e s21_grep.c > a");
system("./s21_grep -h -e inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(he_option3) {
#line 557
system("grep -e inclu.e s21_grep.c -h > a");
system("./s21_grep -e inclu.e s21_grep.c -h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(he_option4) {
#line 562
system("grep -h -e aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -h -e aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(he_option5) {
#line 567
system("grep -h -e inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -h -e inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(he_option6) {
#line 572
system("grep -e inclu.e s21_grep.c -h s21_grep.h > a");
system("./s21_grep -e inclu.e s21_grep.c -h s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hi_option1) {
#line 579
system("grep -h -i aaa s21_grep.c > a");
system("./s21_grep -h -i aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hi_option2) {
#line 584
system("grep -h -i inClu.e s21_grep.c > a");
system("./s21_grep -h -i inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hi_option3) {
#line 589
system("grep -i inClu.e s21_grep.c -h > a");
system("./s21_grep -i inClu.e s21_grep.c -h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hi_option4) {
#line 594
system("grep -h -i aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -h -i aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hi_option5) {
#line 599
system("grep -h -i inClu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -h -i inClu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hi_option6) {
#line 604
system("grep -i inClu.e s21_grep.c -h s21_grep.h > a");
system("./s21_grep -i inClu.e s21_grep.c -h s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

START_TEST(hv_option1) {
#line 610
system("grep -h -v aaa s21_grep.c > a");
system("./s21_grep -h -v aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hv_option2) {
#line 615
system("grep -h -v inclu.e s21_grep.c > a");
system("./s21_grep -h -v inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hv_option6) {
#line 620
system("grep -v inclu.e s21_grep.c -h > a");
system("./s21_grep -v inclu.e s21_grep.c -h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hv_option3) {
#line 625
system("grep -h -v aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -h -v aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hv_option4) {
#line 630
system("grep -h -v inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -h -v inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hv_option5) {
#line 635
system("grep -v inClu.e s21_grep.c -h s21_grep.h > a");
system("./s21_grep -v inClu.e s21_grep.c -h s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hc_option1) {
#line 642
system("grep -h -c aaa s21_grep.c > a");
system("./s21_grep -h -c aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hc_option2) {
#line 647
system("grep -h -c inclu.e s21_grep.c > a");
system("./s21_grep -h -c inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hc_option6) {
#line 652
system("grep -c inclu.e s21_grep.c -h > a");
system("./s21_grep -c inclu.e s21_grep.c -h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hc_option3) {
#line 657
system("grep -h -c aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -h -c aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hc_option4) {
#line 662
system("grep -h -c inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -h -c inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hc_option5) {
#line 667
system("grep -c inClu.e s21_grep.c -h s21_grep.h > a");
system("./s21_grep -c inClu.e s21_grep.c -h s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hl_option1) {
#line 674
system("grep -h -l aaa s21_grep.c > a");
system("./s21_grep -h -l aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hl_option2) {
#line 679
system("grep -h -l inclu.e s21_grep.c > a");
system("./s21_grep -h -l inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hl_option6) {
#line 684
system("grep -l inclu.e s21_grep.c -h > a");
system("./s21_grep -l inclu.e s21_grep.c -h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hl_option3) {
#line 689
system("grep -h -l aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -h -l aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hl_option4) {
#line 694
system("grep -h -l inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -h -l inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hl_option5) {
#line 699
system("grep -l inClu.e s21_grep.c -h s21_grep.h > a");
system("./s21_grep -l inClu.e s21_grep.c -h s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hn_option1) {
#line 706
system("grep -h -n aaa s21_grep.c > a");
system("./s21_grep -h -n aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hn_option2) {
#line 711
system("grep -h -n inclu.e s21_grep.c > a");
system("./s21_grep -h -n inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hn_option6) {
#line 716
system("grep -n inclu.e s21_grep.c -h > a");
system("./s21_grep -n inclu.e s21_grep.c -h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hn_option3) {
#line 721
system("grep -h -n aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -h -n aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hn_option4) {
#line 726
system("grep -h -n inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -h -n inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(hn_option5) {
#line 731
system("grep -n inClu.e s21_grep.c -h s21_grep.h > a");
system("./s21_grep -n inClu.e s21_grep.c -h s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(se_option1) {
#line 738
system("grep -s -e aaa s21_grep.c > a");
system("./s21_grep -s -e aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(se_option2) {
#line 743
system("grep -s -e inclu.e s21_grep.c > a");
system("./s21_grep -s -e inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(se_option6) {
#line 748
system("grep -e inclu.e s21_grep.c -s > a");
system("./s21_grep -e inclu.e s21_grep.c -s > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(se_option3) {
#line 753
system("grep -s -e aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -s -e aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(se_option4) {
#line 758
system("grep -s -e inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -s -e inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(se_option5) {
#line 763
system("grep -e inclu.e s21_grep.c -s s21_grep.h > a");
system("./s21_grep -e inclu.e s21_grep.c -s s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(si_option1) {
#line 770
system("grep -s -i aaa s21_grep.c > a");
system("./s21_grep -s -i aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(si_option2) {
#line 775
system("grep -s -i inClu.e s21_grep.c > a");
system("./s21_grep -s -i inClu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(si_option6) {
#line 780
system("grep -i inClu.e s21_grep.c -s > a");
system("./s21_grep -i inClu.e s21_grep.c -s > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(si_option3) {
#line 785
system("grep -s -i aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -s -i aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(si_option4) {
#line 790
system("grep -s -i inClu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -s -i inClu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(si_option5) {
#line 795
system("grep -i inClu.e s21_grep.c -s s21_grep.h > a");
system("./s21_grep -i inClu.e s21_grep.c -s s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

START_TEST(sv_option1) {
#line 801
system("grep -s -v aaa s21_grep.c > a");
system("./s21_grep -s -v aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sv_option2) {
#line 806
system("grep -s -v inclu.e s21_grep.c > a");
system("./s21_grep -s -v inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sv_option6) {
#line 811
system("grep -v inclu.e s21_grep.c -s > a");
system("./s21_grep -v inclu.e s21_grep.c -s > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sv_option3) {
#line 816
system("grep -s -v aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -s -v aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sv_option4) {
#line 821
system("grep -s -v inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -s -v inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sv_option5) {
#line 826
system("grep -v inClu.e s21_grep.c -s s21_grep.h > a");
system("./s21_grep -v inClu.e s21_grep.c -s s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sc_option1) {
#line 833
system("grep -s -c aaa s21_grep.c > a");
system("./s21_grep -s -c aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sc_option2) {
#line 838
system("grep -s -c inclu.e s21_grep.c > a");
system("./s21_grep -s -c inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sc_option3) {
#line 843
system("grep -c inclu.e s21_grep.c -s > a");
system("./s21_grep -c inclu.e s21_grep.c -s > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sc_option6) {
#line 848
system("grep -s -c aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -s -c aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sc_option4) {
#line 853
system("grep -s -c inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -s -c inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sc_option5) {
#line 858
system("grep -c inClu.e s21_grep.c -s s21_grep.h > a");
system("./s21_grep -c inClu.e s21_grep.c -s s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sl_option1) {
#line 865
system("grep -s -l aaa s21_grep.c > a");
system("./s21_grep -s -l aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sl_option2) {
#line 870
system("grep -s -l inclu.e s21_grep.c > a");
system("./s21_grep -s -l inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sl_option3) {
#line 875
system("grep -l inclu.e s21_grep.c -s > a");
system("./s21_grep -l inclu.e s21_grep.c -s > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sl_option6) {
#line 880
system("grep -s -l aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -s -l aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sl_option4) {
#line 885
system("grep -s -l inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -s -l inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sl_option5) {
#line 890
system("grep -l inClu.e s21_grep.c -s s21_grep.h > a");
system("./s21_grep -l inClu.e s21_grep.c -s s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sn_option1) {
#line 897
system("grep -s -n aaa s21_grep.c > a");
system("./s21_grep -s -n aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sn_option2) {
#line 902
system("grep -s -n inclu.e s21_grep.c > a");
system("./s21_grep -s -n inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sn_option3) {
#line 907
system("grep -n inclu.e s21_grep.c -s > a");
system("./s21_grep -n inclu.e s21_grep.c -s > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sn_option6) {
#line 912
system("grep -s -n aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -s -n aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sn_option4) {
#line 917
system("grep -s -n inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -s -n inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sn_option5) {
#line 922
system("grep -n inClu.e s21_grep.c -s s21_grep.h > a");
system("./s21_grep -n inClu.e s21_grep.c -s s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sh_option1) {
#line 929
system("grep -s -h aaa s21_grep.c > a");
system("./s21_grep -s -h aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sh_option2) {
#line 934
system("grep -s -h inclu.e s21_grep.c > a");
system("./s21_grep -s -h inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sh_option3) {
#line 939
system("grep -h inclu.e s21_grep.c -s > a");
system("./s21_grep -h inclu.e s21_grep.c -s > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sh_option6) {
#line 944
system("grep -s -h aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -s -h aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sh_option4) {
#line 949
system("grep -s -h inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -s -h inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sh_option5) {
#line 954
system("grep -h inClu.e s21_grep.c -s s21_grep.h > a");
system("./s21_grep -h inClu.e s21_grep.c -s s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ef_option1) {
#line 961
system("grep -f s21_grep.c -e aaa s21_grep.c > a");
system("./s21_grep -f s21_grep.c -e aaa s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ef_option2) {
#line 966
system("grep -f s21_grep.c -e inclu.e s21_grep.c > a");
system("./s21_grep -f s21_grep.c -e inclu.e s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ef_option3) {
#line 971
system("grep -e inclu.e s21_grep.c -f s21_grep.c > a");
system("./s21_grep -e inclu.e s21_grep.c -f s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ef_option6) {
#line 976
system("grep -f s21_grep.c -e aaa s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -e aaa s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ef_option4) {
#line 981
system("grep -f s21_grep.c -e inclu.e s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -e inclu.e s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ef_option5) {
#line 986
system("grep -e inclu.e s21_grep.c -f s21_grep.c s21_grep.h > a");
system("./s21_grep -e inclu.e s21_grep.c -f s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fi_option1) {
#line 993
system("grep -f s21_grep.c -i s21_grep.c > a");
system("./s21_grep -f s21_grep.c -i s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fi_option2) {
#line 998
system("grep -f s21_grep.c -i s21_grep.c > a");
system("./s21_grep -f s21_grep.c -i s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fi_option3) {
#line 1003
system("grep -i s21_grep.c -f s21_grep.c > a");
system("./s21_grep -i s21_grep.c -f s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fi_option6) {
#line 1008
system("grep -f s21_grep.c -i s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -i s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fi_option4) {
#line 1013
system("grep -f s21_grep.c -i s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -i s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fi_option5) {
#line 1018
system("grep -i s21_grep.c -f s21_grep.c s21_grep.h > a");
system("./s21_grep -i s21_grep.c -f s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

START_TEST(fv_option1) {
#line 1024
system("grep -f s21_grep.c -v s21_grep.c > a");
system("./s21_grep -f s21_grep.c -v s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fv_option2) {
#line 1029
system("grep -f s21_grep.c -v s21_grep.c > a");
system("./s21_grep -f s21_grep.c -v s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fv_option3) {
#line 1034
system("grep -v s21_grep.c -f s21_grep.c > a");
system("./s21_grep -v s21_grep.c -f s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fv_option6) {
#line 1039
system("grep -f s21_grep.c -v s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -v s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fv_option4) {
#line 1044
system("grep -f s21_grep.c -v s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -v s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fv_option5) {
#line 1049
system("grep -v s21_grep.c -f s21_grep.c s21_grep.h > a");
system("./s21_grep -v s21_grep.c -f s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fc_option1) {
#line 1056
system("grep -f s21_grep.h -c s21_grep.c > a");
system("./s21_grep -f s21_grep.h -c s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fc_option2) {
#line 1061
system("grep -f s21_grep.h -c s21_grep.c > a");
system("./s21_grep -f s21_grep.h -c s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fc_option3) {
#line 1066
system("grep -c s21_grep.h -f s21_grep.c > a");
system("./s21_grep -c s21_grep.h -f s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fc_option6) {
#line 1071
system("grep -f s21_grep.h -c s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.h -c s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fc_option4) {
#line 1076
system("grep -f s21_grep.c -c s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -c s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fc_option5) {
#line 1081
system("grep -c s21_grep.c -f s21_grep.c s21_grep.h > a");
system("./s21_grep -c s21_grep.c -f s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fl_option1) {
#line 1088
system("grep -f s21_grep.c -l s21_grep.c > a");
system("./s21_grep -f s21_grep.c -l s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fl_option2) {
#line 1093
system("grep -f s21_grep.c -l s21_grep.c > a");
system("./s21_grep -f s21_grep.c -l s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fl_option3) {
#line 1098
system("grep -l s21_grep.c -f s21_grep.c > a");
system("./s21_grep -l s21_grep.c -f s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fl_option6) {
#line 1103
system("grep -f s21_grep.c -l s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -l s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fl_option4) {
#line 1108
system("grep -f s21_grep.c -l s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -l s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fl_option5) {
#line 1113
system("grep -l s21_grep.c -f s21_grep.c s21_grep.h > a");
system("./s21_grep -l s21_grep.c -f s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fn_option1) {
#line 1120
system("grep -f s21_grep.c -n s21_grep.c > a");
system("./s21_grep -f s21_grep.c -n s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fn_option2) {
#line 1125
system("grep -f s21_grep.c -n s21_grep.c > a");
system("./s21_grep -f s21_grep.c -n s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fn_option3) {
#line 1130
system("grep -n s21_grep.c -f s21_grep.c > a");
system("./s21_grep -n s21_grep.c -f s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fn_option6) {
#line 1135
system("grep -f s21_grep.c -n s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -n s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fn_option4) {
#line 1140
system("grep -f s21_grep.c -n s21_grep.c s21_grep.h > a");
system("./s21_grep -f s21_grep.c -n s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fn_option5) {
#line 1145
system("grep -n s21_grep.c -f s21_grep.c s21_grep.h > a");
system("./s21_grep -n s21_grep.c -f s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fh_option1) {
#line 1152
system("grep -fs21_grep.c -h s21_grep.c > a");
system("./s21_grep -fs21_grep.c -h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fh_option2) {
#line 1157
system("grep -fs21_grep.c -h s21_grep.c > a");
system("./s21_grep -fs21_grep.c -h s21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fh_option3) {
#line 1162
system("grep -h s21_grep.c -fs21_grep.c > a");
system("./s21_grep -h s21_grep.c -fs21_grep.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fh_option6) {
#line 1167
system("grep -fs21_grep.c -h s21_grep.c s21_grep.h > a");
system("./s21_grep -fs21_grep.c -h s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fh_option4) {
#line 1172
system("grep -fs21_grep.c -h s21_grep.c s21_grep.h > a");
system("./s21_grep -fs21_grep.c -h s21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(fh_option5) {
#line 1177
system("grep -h s21_grep.c -fs21_grep.c s21_grep.h > a");
system("./s21_grep -h s21_grep.c -fs21_grep.c s21_grep.h > b");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

START_TEST(ivncpoint) {
#line 1182
system("grep -c -i -v . s21_grep.c s21_grep.h -n > b");
system("./s21_grep -c -i -v . s21_grep.c s21_grep.h -n > a  ");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

START_TEST(manyflags) {
#line 1187
system("grep -nl -einclude -e print s21_grep.c s21_grep.h -n  -e include -e include -v > b ");
system("./s21_grep -nl -einclude -e print s21_grep.c s21_grep.h -n  -e include -e include -v > a");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

START_TEST(ivwords) {
#line 1192
system("grep -i -v -e INCLUDE -einclude -e int s21_grep.c s21_grep.h -n > b ");
system("./s21_grep -i -v -e INCLUDE -einclude -e int s21_grep.c s21_grep.h -n > a  ");
ck_assert_int_eq(system("diff a b"), 0);}
END_TEST

// START_TEST(ivnpoint) {
// #line 1197
// system("grep -i -v . s21_grep.c s21_grep.h -n > b ");
// system("./s21_grep -i -v . s21_grep.c s21_grep.h -n > a  ");
// ck_assert_int_eq(system("diff a b"), 0);}
// END_TEST

// START_TEST(ivnpoint) {
// #line 1202
// system("grep -i -v . s21_grep.c s21_grep.h -n > b ");
// system("./s21_grep -i -v . s21_grep.c s21_grep.h -n > a  ");
// ck_assert_int_eq(system("diff a b"), 0);}
// END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, emty_option);
    tcase_add_test(tc1_1, e_option1);
    tcase_add_test(tc1_1, e_option2);
    tcase_add_test(tc1_1, e_option3);
    tcase_add_test(tc1_1, e_option4);
    tcase_add_test(tc1_1, e_option5);
    tcase_add_test(tc1_1, e_option6);
    tcase_add_test(tc1_1, e_option7);
    tcase_add_test(tc1_1, e_option8);
    tcase_add_test(tc1_1, e_option9);
    tcase_add_test(tc1_1, e_option10);
    tcase_add_test(tc1_1, i_option1);
    tcase_add_test(tc1_1, i_option2);
    tcase_add_test(tc1_1, i_option3);
    tcase_add_test(tc1_1, i_option4);
    tcase_add_test(tc1_1, i_option5);
    tcase_add_test(tc1_1, i_option6);
    tcase_add_test(tc1_1, v_option1);
    tcase_add_test(tc1_1, v_option2);
    tcase_add_test(tc1_1, v_option3);
    tcase_add_test(tc1_1, v_option4);
    tcase_add_test(tc1_1, v_option5);
    tcase_add_test(tc1_1, v_option6);
    tcase_add_test(tc1_1, c_option1);
    tcase_add_test(tc1_1, c_option2);
    tcase_add_test(tc1_1, c_option3);
    tcase_add_test(tc1_1, c_option4);
    tcase_add_test(tc1_1, c_option5);
    tcase_add_test(tc1_1, c_option6);
    tcase_add_test(tc1_1, n_option1);
    tcase_add_test(tc1_1, n_option2);
    tcase_add_test(tc1_1, n_option3);
    tcase_add_test(tc1_1, n_option4);
    tcase_add_test(tc1_1, n_option5);
    tcase_add_test(tc1_1, n_option6);
    tcase_add_test(tc1_1, l_option1);
    tcase_add_test(tc1_1, l_option2);
    tcase_add_test(tc1_1, l_option3);
    tcase_add_test(tc1_1, l_option4);
    tcase_add_test(tc1_1, l_option5);
    tcase_add_test(tc1_1, l_option6);
    tcase_add_test(tc1_1, ei_option1);
    tcase_add_test(tc1_1, ei_option2);
    tcase_add_test(tc1_1, ei_option3);
    tcase_add_test(tc1_1, ei_option4);
    tcase_add_test(tc1_1, ei_option5);
    tcase_add_test(tc1_1, ei_option6);
    tcase_add_test(tc1_1, ev_option1);
    tcase_add_test(tc1_1, ev_option2);
    tcase_add_test(tc1_1, ev_option3);
    tcase_add_test(tc1_1, ec_option1);
    tcase_add_test(tc1_1, ec_option2);
    tcase_add_test(tc1_1, iv_option1);
    tcase_add_test(tc1_1, iv_option2);
    tcase_add_test(tc1_1, iv_option3);
    tcase_add_test(tc1_1, iv_option4);
    tcase_add_test(tc1_1, iv_option5);
    tcase_add_test(tc1_1, iv_option6);
    tcase_add_test(tc1_1, ic_option1);
    tcase_add_test(tc1_1, ic_option2);
    tcase_add_test(tc1_1, ic_option3);
    tcase_add_test(tc1_1, ic_option4);
    tcase_add_test(tc1_1, ic_option5);
    tcase_add_test(tc1_1, ic_option6);
    tcase_add_test(tc1_1, il_option1);
    tcase_add_test(tc1_1, il_option2);
    tcase_add_test(tc1_1, il_option3);
    tcase_add_test(tc1_1, il_option4);
    tcase_add_test(tc1_1, il_option5);
    tcase_add_test(tc1_1, il_option6);
    tcase_add_test(tc1_1, in_option1);
    tcase_add_test(tc1_1, in_option2);
    tcase_add_test(tc1_1, in_option3);
    tcase_add_test(tc1_1, in_option4);
    tcase_add_test(tc1_1, in_option5);
    tcase_add_test(tc1_1, in_option6);
    tcase_add_test(tc1_1, vc_option1);
    tcase_add_test(tc1_1, vc_option2);
    tcase_add_test(tc1_1, vc_option3);
    tcase_add_test(tc1_1, vc_option4);
    tcase_add_test(tc1_1, vc_option5);
    tcase_add_test(tc1_1, vc_option6);
    tcase_add_test(tc1_1, vl_option1);
    tcase_add_test(tc1_1, vl_option2);
    tcase_add_test(tc1_1, vl_option3);
    tcase_add_test(tc1_1, vl_option4);
    tcase_add_test(tc1_1, vl_option5);
    tcase_add_test(tc1_1, vl_option6);
    tcase_add_test(tc1_1, vn_option1);
    tcase_add_test(tc1_1, vn_option2);
    tcase_add_test(tc1_1, vn_option3);
    tcase_add_test(tc1_1, cl_option1);
    tcase_add_test(tc1_1, cl_option2);
    tcase_add_test(tc1_1, cl_option3);
    tcase_add_test(tc1_1, cn_option1);
    tcase_add_test(tc1_1, cn_option2);
    tcase_add_test(tc1_1, cn_option3);
    tcase_add_test(tc1_1, ln_option1);
    tcase_add_test(tc1_1, ln_option2);
    tcase_add_test(tc1_1, nl_option3);
    tcase_add_test(tc1_1, ivncpoint);
    tcase_add_test(tc1_1, manyflags);
    tcase_add_test(tc1_1, ivwords);
    tcase_add_test(tc1_1, he_option1);
    tcase_add_test(tc1_1, he_option2);
    tcase_add_test(tc1_1, he_option3);
    tcase_add_test(tc1_1, he_option4);
    tcase_add_test(tc1_1, he_option5);
    tcase_add_test(tc1_1, he_option6);
    tcase_add_test(tc1_1, hi_option1);
    tcase_add_test(tc1_1, hi_option2);
    tcase_add_test(tc1_1, hi_option3);
    tcase_add_test(tc1_1, hi_option4);
    tcase_add_test(tc1_1, hi_option5);
    tcase_add_test(tc1_1, hi_option6);
    tcase_add_test(tc1_1, hv_option1);
    tcase_add_test(tc1_1, hv_option2);
    tcase_add_test(tc1_1, hv_option6);
    tcase_add_test(tc1_1, hv_option3);
    tcase_add_test(tc1_1, hv_option4);
    tcase_add_test(tc1_1, hv_option5);
    tcase_add_test(tc1_1, hc_option1);
    tcase_add_test(tc1_1, hc_option2);
    tcase_add_test(tc1_1, hc_option6);
    tcase_add_test(tc1_1, hc_option3);
    tcase_add_test(tc1_1, hc_option4);
    tcase_add_test(tc1_1, hc_option5);
    tcase_add_test(tc1_1, hl_option1);
    tcase_add_test(tc1_1, hl_option2);
    tcase_add_test(tc1_1, hl_option6);
    tcase_add_test(tc1_1, hl_option3);
    tcase_add_test(tc1_1, hl_option4);
    tcase_add_test(tc1_1, hl_option5);
    tcase_add_test(tc1_1, hn_option1);
    tcase_add_test(tc1_1, hn_option2);
    tcase_add_test(tc1_1, hn_option6);
    tcase_add_test(tc1_1, hn_option3);
    tcase_add_test(tc1_1, hn_option4);
    tcase_add_test(tc1_1, hn_option5);
    tcase_add_test(tc1_1, se_option1);
    tcase_add_test(tc1_1, se_option2);
    tcase_add_test(tc1_1, se_option6);
    tcase_add_test(tc1_1, se_option3);
    tcase_add_test(tc1_1, se_option4);
    tcase_add_test(tc1_1, se_option5);
    tcase_add_test(tc1_1, si_option1);
    tcase_add_test(tc1_1, si_option2);
    tcase_add_test(tc1_1, si_option6);
    tcase_add_test(tc1_1, si_option3);
    tcase_add_test(tc1_1, si_option4);
    tcase_add_test(tc1_1, si_option5);
    tcase_add_test(tc1_1, sv_option1);
    tcase_add_test(tc1_1, sv_option2);
    tcase_add_test(tc1_1, sv_option6);
    tcase_add_test(tc1_1, sv_option3);
    tcase_add_test(tc1_1, sv_option4);
    tcase_add_test(tc1_1, sv_option5);
    tcase_add_test(tc1_1, sc_option1);
    tcase_add_test(tc1_1, sc_option2);
    tcase_add_test(tc1_1, sc_option3);
    tcase_add_test(tc1_1, sc_option6);
    tcase_add_test(tc1_1, sc_option4);
    tcase_add_test(tc1_1, sc_option5);
    tcase_add_test(tc1_1, sl_option1);
    tcase_add_test(tc1_1, sl_option2);
    tcase_add_test(tc1_1, sl_option3);
    tcase_add_test(tc1_1, sl_option6);
    tcase_add_test(tc1_1, sl_option4);
    tcase_add_test(tc1_1, sl_option5);
    tcase_add_test(tc1_1, sn_option1);
    tcase_add_test(tc1_1, sn_option2);
    tcase_add_test(tc1_1, sn_option3);
    tcase_add_test(tc1_1, sn_option6);
    tcase_add_test(tc1_1, sn_option4);
    tcase_add_test(tc1_1, sn_option5);
    tcase_add_test(tc1_1, sh_option1);
    tcase_add_test(tc1_1, sh_option2);
    tcase_add_test(tc1_1, sh_option3);
    tcase_add_test(tc1_1, sh_option6);
    tcase_add_test(tc1_1, sh_option4);
    tcase_add_test(tc1_1, sh_option5);
    tcase_add_test(tc1_1, ef_option1);
    tcase_add_test(tc1_1, ef_option2);
    tcase_add_test(tc1_1, ef_option3);
    tcase_add_test(tc1_1, ef_option6);
    tcase_add_test(tc1_1, ef_option4);
    tcase_add_test(tc1_1, ef_option5);
    tcase_add_test(tc1_1, fi_option1);
    tcase_add_test(tc1_1, fi_option2);
    tcase_add_test(tc1_1, fi_option3);
    tcase_add_test(tc1_1, fi_option6);
    tcase_add_test(tc1_1, fi_option4);
    tcase_add_test(tc1_1, fi_option5);
    tcase_add_test(tc1_1, fv_option1);
    tcase_add_test(tc1_1, fv_option2);
    tcase_add_test(tc1_1, fv_option3);
    tcase_add_test(tc1_1, fv_option6);
    tcase_add_test(tc1_1, fv_option4);
    tcase_add_test(tc1_1, fv_option5);
    tcase_add_test(tc1_1, fc_option1);
    tcase_add_test(tc1_1, fc_option2);
    tcase_add_test(tc1_1, fc_option3);
    tcase_add_test(tc1_1, fc_option6);
    tcase_add_test(tc1_1, fc_option4);
    tcase_add_test(tc1_1, fc_option5);
    tcase_add_test(tc1_1, fl_option1);
    tcase_add_test(tc1_1, fl_option2);
    tcase_add_test(tc1_1, fl_option3);
    tcase_add_test(tc1_1, fl_option6);
    tcase_add_test(tc1_1, fl_option4);
    tcase_add_test(tc1_1, fl_option5);
    tcase_add_test(tc1_1, fn_option1);
    tcase_add_test(tc1_1, fn_option2);
    tcase_add_test(tc1_1, fn_option3);
    tcase_add_test(tc1_1, fn_option6);
    tcase_add_test(tc1_1, fn_option4);
    tcase_add_test(tc1_1, fn_option5);
    tcase_add_test(tc1_1, fh_option1);
    tcase_add_test(tc1_1, fh_option2);
    tcase_add_test(tc1_1, fh_option3);
    tcase_add_test(tc1_1, fh_option6);
    tcase_add_test(tc1_1, fh_option4);
    tcase_add_test(tc1_1, fh_option5);

    srunner_set_fork_status(sr, CK_NOFORK);
    srunner_run_all(sr, CK_NORMAL);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
