/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#line 1 "test.check"
#include "s21_cat.h"

START_TEST(emty_option) {
#line 4
system("cat s21_cat.h > a");
system("./s21_cat s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(b_option) {
#line 9
system("cat -b s21_cat.h > a");
system("./s21_cat -b s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(e_option) {
#line 14
system("cat -e s21_cat.h > a");
system("./s21_cat -e s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(n_option) {
#line 19
system("cat -n s21_cat.h > a");
system("./s21_cat -n s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(s_option) {
#line 24
system("cat -s s21_cat.h > a");
system("./s21_cat -s s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(t_option) {
#line 29
system("cat -t s21_cat.h > a");
system("./s21_cat -t s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(be_option) {
#line 34
system("cat -be s21_cat.h > a");
system("./s21_cat -be s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bn_option) {
#line 39
system("cat -bn s21_cat.h > a");
system("./s21_cat -bn s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bs_option) {
#line 44
system("cat -bs s21_cat.h > a");
system("./s21_cat -bs s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bt_option) {
#line 49
system("cat -bt s21_cat.h > a");
system("./s21_cat -bt s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(en_option) {
#line 54
system("cat -en s21_cat.h > a");
system("./s21_cat -en s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(es_option) {
#line 59
system("cat -es s21_cat.h > a");
system("./s21_cat -es s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(et_option) {
#line 64
system("cat -et s21_cat.c > a");
system("./s21_cat -et s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ns_option) {
#line 69
system("cat -ns s21_cat.h > a");
system("./s21_cat -ns s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(nt_option) {
#line 74
system("cat -nt s21_cat.c > a");
system("./s21_cat -nt s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(sn_option) {
#line 79
system("cat -sn s21_cat.h > a");
system("./s21_cat -sn s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(st_option) {
#line 84
system("cat -st s21_cat.h > a");
system("./s21_cat -st s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ben_option) {
#line 89
system("cat -ben s21_cat.c > a");
system("./s21_cat -ben s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bes_option) {
#line 94
system("cat -bes s21_cat.h > a");
system("./s21_cat -bes s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bet_option) {
#line 99
system("cat -bet s21_cat.h > a");
system("./s21_cat -bet s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bns_option) {
#line 104
system("cat -bns s21_cat.h > a");
system("./s21_cat -bns s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bnt_option) {
#line 109
system("cat -bnt s21_cat.c > a");
system("./s21_cat -bnt s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ens_option) {
#line 114
system("cat -ens s21_cat.h > a");
system("./s21_cat -ens s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(ent_option) {
#line 119
system("cat -ent s21_cat.h > a");
system("./s21_cat -ent s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(nst_option) {
#line 124
system("cat -nst s21_cat.h > a");
system("./s21_cat -nst s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bens_option) {
#line 129
system("cat -bens s21_cat.h > a");
system("./s21_cat -bens s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(bent_option) {
#line 134
system("cat -bent s21_cat.c > a");
system("./s21_cat -bent s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(enst_option) {
#line 139
system("cat -enst s21_cat.h > a");
system("./s21_cat -enst s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(benst_option) {
#line 144
system("cat -benst s21_cat.c > a");
system("./s21_cat -benst s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(s_empty_end) {
system("cat -s s21_cat.c > a");
system("./s21_cat -s s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(new_flags) {
system("cat -n -b -s -t s21_cat.c > a");
system("./s21_cat -n -b -s -t s21_cat.c > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(many_files) {
system("cat -bnste s21_cat.c s21_cat.h > a");
system("./s21_cat -bnste s21_cat.c s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

START_TEST(flags_after) {
system("cat -bnste -s -n s21_cat.c s21_cat.h > a");
system("./s21_cat -bnste -s -n s21_cat.c s21_cat.h > b");
ck_assert_int_eq(system("diff a b"), 0);
}
END_TEST

int main(void) {
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, emty_option);
    tcase_add_test(tc1_1, b_option);
    tcase_add_test(tc1_1, e_option);
    tcase_add_test(tc1_1, n_option);
    tcase_add_test(tc1_1, s_option);
    tcase_add_test(tc1_1, t_option);
    tcase_add_test(tc1_1, be_option);
    tcase_add_test(tc1_1, bn_option);
    tcase_add_test(tc1_1, bs_option);
    tcase_add_test(tc1_1, bt_option);
    tcase_add_test(tc1_1, en_option);
    tcase_add_test(tc1_1, es_option);
    tcase_add_test(tc1_1, et_option);
    tcase_add_test(tc1_1, ns_option);
    tcase_add_test(tc1_1, nt_option);
    tcase_add_test(tc1_1, sn_option);
    tcase_add_test(tc1_1, st_option);
    tcase_add_test(tc1_1, ben_option);
    tcase_add_test(tc1_1, bes_option);
    tcase_add_test(tc1_1, bet_option);
    tcase_add_test(tc1_1, bns_option);
    tcase_add_test(tc1_1, bnt_option);
    tcase_add_test(tc1_1, ens_option);
    tcase_add_test(tc1_1, ent_option);
    tcase_add_test(tc1_1, nst_option);
    tcase_add_test(tc1_1, bens_option);
    tcase_add_test(tc1_1, bent_option);
    tcase_add_test(tc1_1, enst_option);
    tcase_add_test(tc1_1, benst_option);
    tcase_add_test(tc1_1, s_empty_end);
    tcase_add_test(tc1_1, new_flags);
    tcase_add_test(tc1_1, many_files);
    tcase_add_test(tc1_1, flags_after);

    srunner_set_fork_status(sr, CK_NOFORK);
    srunner_run_all(sr, CK_NORMAL);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
